# Generated by Django 5.0.6 on 2024-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=300)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('LinkedIn', models.URLField(blank=True)),
                ('GitHub', models.URLField(blank=True)),
            ],
        ),
    ]
